### ISSUE TITLE
In den Warenkorb auf jedem Artikel ermöglichen

### ISSUE THREAD

**Issue by polarpixel** [thielpeter/flexshop#1]
Wenn ich es richtig sehe, ist es im Moment nur möglich, einen Artikel in den Warenkorb zu legen über den Link auf die Warenkorb-Seite. Dadurch ist vermutlich nicht möglich, nach dem In-den-Warenkorb-Legen ein Popup zu machen mit den beiden Links "Zum Warenkorb" und "Weiter einkaufen".
Hast Du hier eine Idee für eine Lösung?

**Comment by thielpeter** [comment]
Ist im nächsten Release verfügbar
