### ISSUE TITLE
Anzahl der Warenkorb-Artikel sofort aktualisieren

### ISSUE THREAD

**Issue by polarpixel** [thielpeter/flexshop#2]
Wenn man einen Artikel in den Warenkorb legt, ist die geänderte Zahl der Artikel im Warenkorb (REX_FLEXSHOP[cart=light]) erst nach dem nächsten Laden der Seite sichtbar.
Gibt s eine Möglichkeit, dies gleich aktuell zu zeigen?

**Comment by thielpeter** [comment]
Ist im nächsten Release verfügbar
